### ISSUE TITLE
INFO/TIP: socat logs 127.0.0.1 in smtp-1...

### ISSUE THREAD

**Issue by krull** [zdeneksvarc/postal-tls#2]
Hello there!

Great job on the write up / howto here thus far. I have successfully been using this to add STARTTLS to my `postal` install.

One suggestion since I also needed to have [fail2ban](https://github.com/maticomba/postal-smtp-fail2ban) to the mix which requires to write to a log file, that your `socat` docker redirect from port 587 to port 25, records `socat` running at `127.0.0.1` instead of `$SOCAT_PEERADDR` in the static logfile.

I remedied this by using iptables for the PREROUTING instead of `socat` like so:

`iptables -t nat -I PREROUTING -p tcp --dport 587 -j REDIRECT --to-port 25
`

I commented out your `port-587` docker-compose entry so it doesn't fire up when starting `docker-compose up -d`, and I get all the benefits of 'Received over a SSL connection' as intended.

Keep up the great work!

@krull

**Comment by zdeneksvarc** [comment]
Thanks for the idea. Yes, iptables is also an option. I wanted to keep a lean containerized system without interfering with the host system. Therefore socat.
