### ISSUE TITLE
Different SSL for hostname and SMTP

### ISSUE THREAD

**Issue by sujitph** [zdeneksvarc/postal-tls#4]
Hi there,

This is not an issue, but more of a question.

Is there a way to have different SSL for hostname and SMTP. For example, I'd like to access postal web panel on postal.xxx.com and smtp and other ports on mail.xxx.com. Any way to have different certs or probably generate wildcard ssl to serve different subdomains.

Thanks,

**Comment by zdeneksvarc** [comment]
Sure, you can use wildcard certificate, but to do that you have to use DNS-01 challenge, https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

So use e.g. Certbot outside of Caddy.

**Comment by sujitph** [comment]
> Sure, you can use wildcard certificate, but to do that you have to use DNS-01 challenge, https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates
> 
> So use e.g. Certbot outside of Caddy.

Thank you
Will try using certbot.
